#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/Serveur-Web-Prive1 ./files/Serveur-Web-Prive1/var/scripts/init
  cp ./scripts/Box1 ./files/Box1/etc/scripts/init
  cp ./scripts/Box2 ./files/Box2/etc/scripts/init
  cp ./scripts/Routeur-FAI ./files/Routeur-FAI/etc/scripts/init
  cp ./scripts/Routeur1 ./files/Routeur1/etc/scripts/init
  cp ./scripts/Routeur2 ./files/Routeur2/etc/scripts/init
  cp ./scripts/Routeur-Services-Reseaux ./files/Routeur-Services-Reseaux/etc/scripts/init
  cp ./scripts/Routeur-Services ./files/Routeur-Services/etc/scripts/init
  cp ./scripts/Serveur-Web ./files/Serveur-Web/var/scripts/init
  cp ./scripts/Serveur-DNS ./files/Serveur-DNS/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
